apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "file-manager-server.fullname" . }}
  labels:
    {{- include "file-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    objectStore:
      s3:
        endpointUrl: {{ .Values.objectStore.s3.endpointUrl }}
        bucket: {{ .Values.objectStore.s3.bucket }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.database.username }}
      passwordEnvName: {{ .Values.database.passwordEnvName }}
