apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "file-manager-vstore.fullname" . }}
  labels:
    {{- include "file-manager-vstore.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    auth:
      enable: {{ .Values.global.auth.enable }}
      rbacInternalServerAddr: {{ .Values.global.auth.rbacInternalServerAddr }}
