apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "file-manager-vstore.fullname" . }}-http
  labels:
    {{- include "file-manager-vstore.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - path: /v1/vector_stores
        pathType: Prefix
        backend:
          service:
            name: {{ include "file-manager-vstore.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}
