global:
  database:
    host:
    port:
    username:

  databaseSecret:
    name:
    key:

  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable:
    rbacInternalServerAddr:

  workerServiceGrpcService:
    annotations:

  workerServiceIngress:
    create: false
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

httpPort: 8080
grpcPort: 8081
workerServiceGrpcPort: 8082

database:
  database: file_manager

objectStore:
  s3:
    pathPrefix: files

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/file-manager-server
  pullPolicy: IfNotPresent

version:
