global:
  database:
    host:
    port:
    username:
    passwordEnvName:

  databaseSecret:
    name:
    key:

  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

  ingress:
    ingressClassName:

httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8082

database:
  database: file_manager

objectStore:
  s3:
    pathPrefix: files

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/file-manager-server
  pullPolicy: IfNotPresent

version:
